export PLUGIN_REPO so it's available in the label utility
Prevents the confusing an unexpected error:

    Error: No such object:

Signed-off-by: Joe Groocock <me@frebib.net>